apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-ca
  namespace: hlf
  labels:
    app: tls-ca
spec:
  selector:
    matchLabels:
      app: tls-ca
  template:
    metadata:
      labels:
        app: tls-ca
    spec:
      containers:
        - name: tls-ca
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["fabric-ca-server", "start", "-b", "$(BOOTSTRAP_USER):$(BOOTSTRAP_PASSWORD)", "--port", "7052"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/tmp/hyperledger/scripts/startNetwork/registerUsers/registerTlsUsers.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/fabric-ca/crypto
              name: tls-ca-persistent-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/secrets/cert.pem
              name: cert
              subPath: cert.pem
              readOnly: true
            - mountPath: /tmp/secrets/key.pem
              name: key
              subPath: key.pem
              readOnly: true
          env:
            - name: FABRIC_CA_HOME
              value: "/tmp/hyperledger/fabric-ca/crypto"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "tls-ca"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "172.17.0.2,172.17.0.3,0.0.0.0,tls-ca.hlf"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: "/tmp/secrets/cert.pem"
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: "/tmp/secrets/key.pem"
            - name: BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls-ca
                  key: username
            - name: BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls-ca
                  key: password
            - name: ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.orderer-org0
                  key: username
            - name: ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.orderer-org0
                  key: password
            - name: PEER1_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org1
                  key: username
            - name: PEER1_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org1
                  key: password
            - name: PEER2_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer2-org1
                  key: username
            - name: PEER2_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer2-org1
                  key: password
            - name: PEER1_ORG2_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org2
                  key: username
            - name: PEER1_ORG2_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org2
                  key: password
            - name: PEER2_ORG2_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer2-org2
                  key: username
            - name: PEER2_ORG2_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer2-org2
                  key: password
      volumes:
        - name: tls-ca-persistent-mount 
          persistentVolumeClaim:
            claimName: tls-ca-pvc
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: cert
          secret:
            secretName: cert.tls-ca
        - name: key
          secret:
            secretName: key.tls-ca
---
apiVersion: v1
kind: Service
metadata:
  name: tls-ca
  namespace: hlf
  labels:
    app: tls-ca
spec:
  type: NodePort
  selector:
    app: tls-ca
  ports:
    - name: https
      protocol: TCP
      nodePort: 30905
      port: 7052
