apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-org2
  namespace: hlf
  labels:
    app: peer1-org2
spec:
  selector:
    matchLabels:
      app: peer1-org2
  template:
    metadata:
      labels:
        app: peer1-org2
    spec:
      containers:
        - name: peer1-org2
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/org2/peer1
              name: peer1-org2-mount
          env:
            - name: CORE_PEER_ID
              value: "peer1-org2"
            - name: CORE_PEER_LOCALMSPID
              value: "org2MSP"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/org2/peer1/msp"
            - name: CORE_VM_ENDPOINT
              value: "tcp://dind:2375"
            - name: FABRIC_LOGGING_SPEC
              value: "debug:gossip,msp=info"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/tmp/hyperledger/org2/peer1/tls-msp/signcerts/cert.pem"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/tmp/hyperledger/org2/peer1/tls-msp/keystore/key.pem"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/org2/peer1/tls-msp/tlscacerts/tls-tls-ca-hlf-7052.pem"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer1-org2:7051"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
        - name: couchdb
          image: hyperledger/fabric-couchdb:latest
          ports:
            - containerPort: 5984
      volumes:
        - name: peer1-org2-mount
          hostPath:
            path: /mnt/hyperledger/org2/peer1
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-org2
  namespace: hlf
  labels:
    app: peer1-org2
spec:
  type: NodePort
  selector:
    app: peer1-org2
  ports:
    - name: core
      protocol: TCP
      targetPort: 7051
      port: 7051
      nodePort: 30211
    - name: chaincode
      protocol: TCP
      targetPort: 7052
      port: 7052
      nodePort: 30212
