apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer1-org1
  namespace: hlf
  labels:
    app: peer1-org1
spec:
  selector:
    matchLabels:
      app: peer1-org1
  template:
    metadata:
      labels:
        app: peer1-org1
    spec:
      containers:
        - name: peer1-org1
          image: hyperledger/fabric-peer:2.2
          volumeMounts:
            - mountPath: /tmp/hyperledger/org1/peer1
              name: peer1-org1-mount
          env:
            - name: CORE_PEER_ID
              value: "peer1-org1"
            - name: CORE_PEER_LISTENADDRESS
              value: "0.0.0.0:7051"
            - name: CORE_PEER_ADDRESS
              value: "peer1-org1:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "org1MSP"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/org1/peer1/msp"
            - name: CORE_VM_ENDPOINT
              value: "tcp://localhost:2375"
            - name: FABRIC_LOGGING_SPEC
              value: "debug:gossip,msp=info"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/tmp/hyperledger/org1/peer1/tls-msp/signcerts/cert.pem"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/tmp/hyperledger/org1/peer1/tls-msp/keystore/key.pem"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/org1/peer1/tls-msp/tlscacerts/tls-tls-ca-hlf-7052.pem"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer1-org1:7051"
            - name: CORE_PEER_BOOTSTRAP
              value: "peer1-org1:7051"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "peer1-org1:7052"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "0.0.0.0:7052"
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
          ports:
            - containerPort: 7052
        - name: couchdb
          image: hyperledger/fabric-couchdb:latest
          ports:
            - containerPort: 5984
        - name: dind
          image: "docker:18.05.0-dind"
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375
      initContainers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollPeer.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/org1/peer1
              name: peer1-org1-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org1
              name: rca-org1-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: PEER_NUM
              value: "1"
            - name: ORG_NUM
              value: "1"
            - name: ORG_CA_PORT
              value: "7052"
            - name: PEER_TLS_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org1
                  key: username
            - name: PEER_TLS_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer1-org1
                  key: password
            - name: PEER_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.peer1-org1
                  key: username
            - name: PEER_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.peer1-org1
                  key: password
            
      volumes:
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: shared-volume
          hostPath:
            path: /mnt/hyperledger/shared
        - name: peer1-org1-mount
          emptyDir: {}
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-org1-cert
          secret:
            secretName: cert.rca-org1
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-org1
  namespace: hlf
  labels:
    app: peer1-org1
spec:
  type: NodePort
  selector:
    app: peer1-org1
  ports:
    - name: core
      protocol: TCP
      port: 7051
      nodePort: 30111

