apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-org0
  namespace: hlf
  labels:
    app: orderer-org0
spec:
  selector:
    matchLabels:
      app: orderer-org0
  template:
    metadata:
      labels:
        app: orderer-org0
    spec:
      containers:
        - name: orderer-org0
          image: hyperledger/fabric-orderer:2.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/hyperledger/org0/orderer
              name: orderer-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
          env:
            - name: ORDERER_HOME
              value: "/tmp/hyperledger/orderer"
            - name: ORDERER_HOST
              value: "orderer-org0"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/tmp/hyperledger/shared/channel/genesis.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "org0MSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/tmp/hyperledger/org0/orderer/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/tmp/hyperledger/org0/orderer/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/tmp/hyperledger/org0/orderer/tls-msp/tlscacerts/tls-tls-ca-hlf-7052.pem]"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: "debug"
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"
            - name: ORDERER_DEBUG_BROADCASTTRACEDIR
              value: "data/logs"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: "/tmp/hyperledger/org0/orderer/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: "/tmp/hyperledger/org0/orderer/tls-msp/signcerts/cert.pem"
      initContainers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollOrdererOrg0.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/org0/orderer
              name: orderer-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org0
              name: rca-org0-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
        - name: fabric-tools
          image: hyperledger/fabric-tools:2.2.1
          imagePullPolicy: IfNotPresent
          command: ["bash", "/tmp/hyperledger/scripts/startNetwork/createGenesisBlock.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/configmaps
              name: configtx
              readOnly: true
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org0
              name: rca-org0-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org1
              name: rca-org1-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org2
              name: rca-org2-cert
              readOnly: true
      volumes:
        - name: orderer-mount
          emptyDir: {}
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: shared-volume
          hostPath:
            path: /mnt/hyperledger/shared
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-org0-cert
          secret:
            secretName: cert.rca-org0
        - name: rca-org1-cert
          secret:
            secretName: cert.rca-org1
        - name: rca-org2-cert
          secret:
            secretName: cert.rca-org2
        - name: configtx
          configMap:
            name: configtx
---
apiVersion: v1
kind: Service
metadata:
  name: orderer-org0
  namespace: hlf
  labels:
    app: orderer-org0
spec:
  type: NodePort
  selector:
    app: orderer-org0
  ports:
    - protocol: TCP
      targetPort: 7050
      port: 7050
      nodePort: 30010
